=== mjkoster/ODM-Examples/relation/example-schema.json
{
  "title": "Object Model Demo",
  "description": "Schema for instances of an example Object MOdel ",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "Equipment": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "manufacturerName": {
            "type": "string"
          },
          "ActorType": {
            "$ref": "#/definitions/ActorTypeEnum"
          },
          "has.Component": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "json-pointer"
            },
            "relationType": "has",
            "relatedClass": "Component",
            "minItems": 1
          },
          "has.Component.alias": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "json-pointer"
            },
            "relationType": "has",
            "relatedClass": "Component",
            "relationSubType": "alias",
            "minItems": 1,
            "maxItems": 1
          }
        }
      }
    },
    "Component": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "manufacturerName": {
            "type": "string"
          },
          "ActorType": {
            "$ref": "#/definitions/ActorTypeEnum"
          }
        }
      }
    }
  },
  "definitions": {
    "ActorTypeEnum": {
      "enum": [
        "Branch",
        "Consumer",
        "Mixer",
        "Path",
        "Producer",
        "Router",
        "Store",
        "Transformer",
        "Transport",
        "Separator"
      ]
    }
  }
}

=== mjkoster/ODM-Examples/relation/example-instance.json
{
  "id": "f89aca57-e52e-4495-9393-1a306f5cb1d2",
  "name": "test",
  "description": "test",
  "Equipment": {
    "test": {
      "manufacturerName": "",
      "ActorType": "Router",
      "has.Component": [
        "#/Component/test"
      ],
      "has.Component.alias": [
        "#/Component/test"
      ]
    }
  },
  "Component": {
    "test": {
      "manufacturerName": "test",
      "ActorType": "Router"
    }
  }
}
